name: Corretor de Exercícios

on:
  push:
  workflow_dispatch:

jobs:
  aula02:
    name: aula02
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/logica-de-programacao/aula02
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula03:
  name: aula03
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula03
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula08:
  name: aula08
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula08
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula09:
  name: aula09
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula09
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula11:
  name: aula11
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula11
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula12:
  name: aula12
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula12
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula13:
  name: aula13
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula13
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula17:
  name: aula17
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula17
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula26:
  name: aula26
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula26
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula27:
  name: aula27
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula27
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula31:
  name: aula31
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula31
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test

  aula32:
  name: aula32
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: 3-bimestre/logica-de-programacao/aula32
  steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test